services:
  web:
    image: imagejs
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: citacoes
    ports:
      - "8080:80"                 # Mapeamento de portas
    volumes:
      - .:/usr/share/nginx/html   # Sincronização dos arquivos locais